name: 'pr-review'
on: [pull_request]
jobs:
  job1:
    name: 'code-review'
    runs-on: ubuntu-latest
    steps:
      - name: first
        uses: SuneetBansal/ai-driven-pr-review@main
        with:
          openai-key: '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'
      
    
    
