name: Cron Test

on:
  schedule:
    - cron: "*/1 * * * *" # Every minute

jobs:
  test-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Echo current time
        run: echo "The time is $(date)"
